# Generated by Django 2.2.1 on 2019-05-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='nova_group',
            field=models.IntegerField(),
        ),
    ]
