# Generated by Django 2.2.1 on 2019-05-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190516_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='nova_group',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='nutrition_group',
            field=models.CharField(max_length=1, verbose_name='Groupe nutritionnel'),
        ),
    ]
